tema <- theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        text=element_text(family='Lato'),
        plot.title = element_text(size=16,hjust=0.0,face='bold'),
        plot.subtitle = element_text(size=14,hjust=0.0,face='italic'),
        plot.caption = element_text(size=10,face='italic',color='gray'),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=12,face='bold',color='black',hjust=1,vjust=0.2),
        legend.position="none",
        legend.title = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size=12,face='bold',hjust = 0.5),
        legend.text = element_text(color = "black", size = 14,face='bold'),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())
